accounts/urls.py
from django.urls import path
from accounts.views import user_login, user_logout, signup

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('logout/', user_logout, name="logout"),
    path('login/', user_login,name='login'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def home_page(request):
    return redirect('home')

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', home_page, name='home'),
    path('receipts/', include('receipts.urls')),
    path("admin/", admin.site.urls),
]

receipts/urls.py
from django.urls import path
from receipts.views import receipt_list, create_receipt, expense_category_list, account_list, create_category, create_account


urlpatterns = [
    path('accounts/create/', create_account, name='create_account'),
    path('categories/create/', create_category, name="create_category"),
    path('categories/', expense_category_list, name='category_list'),
    path('accounts/', account_list, name='account_list'),
    path('create/', create_receipt, name='create_receipt'),
    path('', receipt_list, name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner= models.ForeignKey(User, related_name="categories", on_delete=models.CASCADE)



class Account(models.Model):
    name = models.CharField(max_length=100)
    number= models.CharField(max_length=20)
    owner= models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE)

class Receipt(models.Model):
    vendor= models.CharField(max_length=200)
    total= models.DecimalField(max_digits=10, decimal_places=3)
    tax= models.DecimalField(max_digits=10, decimal_places=3)
    date= models.DateTimeField()
    purchaser= models.ForeignKey(User, related_name="receipts", on_delete=models.CASCADE)
    category= models.ForeignKey(ExpenseCategory, related_name="receipts", on_delete=models.CASCADE)
    account= models.ForeignKey(Account, related_name="receipts", on_delete=models.CASCADE, null=True)



# Create your models here.

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput,)

class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

receipts/forms.py
from django.forms import ModelForm
from receipts.models import Receipt, ExpenseCategory, Account

class ReceiptForm(ModelForm):
    class Meta:
        model = Receipt
        fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']


class ExpenseCategoryForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name', ]

class AccountForm(ModelForm):
    class Meta:
        model= Account
        fields = ['name', 'number']

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, SignUpForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
# Create your views here.
def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()
    context = {
        "form": form
    }
    return render(request,"accounts/login.html", context)

def user_logout(request):
    logout(request)
    return redirect('login')

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(username, password=password)
                login(request, user)
                return redirect('home')
    else:
        form =SignUpForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from receipts.models import Receipt, ExpenseCategory, Account
from django.contrib.auth.decorators import login_required
from receipts.forms import ReceiptForm, ExpenseCategoryForm, AccountForm

@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {
        'receipts': receipts
    }
    return render(request, 'receipts/receipt_list.html', context)
# Create your views here.

@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect('home')
    else:
        form = ReceiptForm()
    context ={
        "form": form,
    }
    return render(request, 'receipts/create_receipt.html', context)

@login_required
def expense_category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {
        'categories': categories,
        'receipts':receipts
    }
    return render(request,'categories/category_list.html',context)
@login_required
def account_list(request):
    accounts= Account.objects.filter(owner=request.user)
    context = {
        'accounts':accounts
    }
    return render(request, 'accounts/account_list.html',context)

@login_required
def create_category(request):
    if request.method == "POST":
        form = ExpenseCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(False)
            category.owner = request.user
            category.save()
            return redirect('category_list')
    else:
        form = ExpenseCategoryForm()
    context = {
        "form": form,
    }
    return render(request, 'categories/create_category.html', context)

@login_required
def create_account(request):
    if request.method == "POST":
        form= AccountForm(request.POST)
        if form.is_valid():
            account = form.save(False)
            account.owner = request.user
            account.save()
            return redirect('account_list')
    else:
        form =AccountForm()
    context = {
        "form": form,
    }
    return render(request, 'accounts/create_account.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

    {% block title %}Login{% endblock title %}

    {% block content %}
        <div>
            <h1>Login</h1>
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
            </form>
        </div>
    {% endblock content %}

accounts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <header>
      <h1>My Spend Manager</h1>
    </header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'create_category' %}">Create Category</a></li>
          <li><a href="{% url 'account_list' %}">Account List</a></li>
          <li><a href="{% url 'category_list' %}">Category List</a></li>
          <li><a href="{% url 'home' %}">Receipt List</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

receipts/templates/accounts/account_list.html
{% extends 'base.html' %}
{% block title %}Accounts{% endblock title %}
{% block content %}
  <h1>Accounts</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for account in accounts %}
        <tr>
          <td>{{ account.name }}</td>
          <td>{{ account.number }}</td>
          <td>{{ account.receipt_set.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

receipts/templates/accounts/create_account.html
{% extends 'base.html' %}

{% block title %}Create Account{% endblock %}

{% block content %}
  <div>
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
{% endblock %}

receipts/templates/categories/category_list.html
{% extends 'base.html' %}
{% block title %}Expense Categories{% endblock title %}
{% block content %}
  <h1>Expense Categories</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <td>{{ category.name }}</td>
          <td>{{ category.receipt_set.count }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

receipts/templates/categories/create_category.html
{% extends 'base.html' %}

{% block title %}Create Category{% endblock %}

{% block content %}
  <div>
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
{% endblock %}

receipts/templates/receipts/create_receipt.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
{% endblock %}

receipts/templates/receipts/receipt_list.html
{% extends 'base.html' %}

    {% block content %}
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipts %}
                <tr>
                <td>{{ receipt.vendor }}</td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date|date:"m/d/y" }}</td>
                <td>{{ receipt.category.name }}</td>
                <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
    {% endblock content %}